version: '3.8'

services:
  # Capa de Aplicación (PHP 8.2 + Apache)
  # Esta capa almacena información de los usuarios registrados en el e-commerce.
  cartmonitor-app:
    build: .
    container_name: cartmonitor_app
    ports:
      - "8081:80" # Evitamos el 8080. Acceso vía http://localhost:8081
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=cartmonitor-db
      - DB_NAME=CartMonitor
      - DB_USER=CartMonitor_user
      - DB_PASS=CartMonitor_password
    networks:
      - cartmonitor-network

  # Capa de Datos (MySQL 8.0)
  # Esta capa almacena información de los usuarios registrados en el e-commerce.
  cartmonitor-db:
    image: mysql:8.0
    container_name: cartmonitor_db
    restart: always
    environment:
      MYSQL_DATABASE: CartMonitor
      MYSQL_USER: CartMonitor_user
      MYSQL_PASSWORD: CartMonitor_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306" # Mapeo externo 3307 para no chocar con MySQLs locales
    volumes:
      - cartmonitor_db_data:/var/lib/mysql
      - ./database/cartmonitor.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - cartmonitor-network

# Con este comando se crea una red virtual entre los contenedores
networks:
  cartmonitor-network:
    driver: bridge

# Con este comando se crea un volumen para persistir los datos de la base de datos
volumes:
  cartmonitor_db_data:
